import fetch from "node-fetch";
import dotenv from "dotenv";

dotenv.config();

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
// Use a model that exists in your ListModels output and supports generateContent
const GEMINI_MODEL = "gemini-2.5-flash";

export async function generateChexnetReport(patient, analysisResult) {
  if (!GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY is not set in environment variables");
  }

  // analysisResult is an object: { label: score, ... }
  const entries = Object.entries(analysisResult || {}).filter(
    ([, v]) => typeof v === "number"
  );

  const findings =
    entries
      .map(([label, score]) => {
        const logit = Number(score);
        const probApprox = 1 / (1 + Math.exp(-logit)); // sigmoid approx
        return `${label}: score=${logit.toFixed(3)} (${probApprox.toFixed(
          3
        )} approx probability)`;
      })
      .join("\n") || "No valid numeric findings were produced by the model.";

  const prompt = `
You are a radiology assistant. You receive CheXNet model outputs for a chest X-ray.

Patient details:
- Name: ${patient.fullName || "N/A"}
- Age: ${patient.age || "N/A"}
- Gender: ${patient.gender || "N/A"}
- Scan type: ${patient.scanType || "xray"}
- Overall abnormality confidence (higher = more confident scan is normal): ${patient.confidence}% 
- Model assessment: ${patient.isAbnormal ? "Flagged as abnormal" : "Likely normal"}

Model raw scores (logits or uncalibrated):
${findings}

Instructions:
1. Clearly state whether the overall findings suggest a normal or abnormal scan.
2. Highlight only the top 3–5 most relevant findings (by highest scores).
3. Then give a brief technical note for clinicians (2–4 bullet points).
4. Include a short confidentiality and safety note (for example: data is handled securely, this is not a medical diagnosis).
5. Do NOT mention that these are "logits" or implementation details.

Return the answer in plain text, no markdown.
`;

  // Use v1beta endpoint as in your ListModels call
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${GEMINI_API_KEY}`;

  const body = {
    contents: [
      {
        role: "user",
        parts: [{ text: prompt }],
      },
    ],
  };

  const resp = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });

  if (!resp.ok) {
    const errText = await resp.text();
    throw new Error(
      `Gemini API error ${resp.status}: ${errText || resp.statusText}`
    );
  }

  const data = await resp.json();
  const text =
    data?.candidates?.[0]?.content?.parts?.[0]?.text ||
    "No report generated by Gemini.";

  return text.trim();
}





export async function generateCtReport(patient, analysisResult) {
  if (!GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY is not set in environment variables");
  }

  // analysisResult from run_ctscan.py:
  // { classes: [...], scores: { COVID: 0.xx, Pneumonia: 0.xx, Normal: 0.xx }, top_class: "..." }
  const scoresObj =
    analysisResult && typeof analysisResult === "object"
      ? analysisResult.scores || analysisResult
      : {};

  const entries = Object.entries(scoresObj).filter(
    ([, v]) => typeof v === "number"
  );

  const findings =
    entries
      .map(([label, prob]) => {
        const p = Number(prob);
        return `${label}: ${(p * 100).toFixed(2)}%`;
      })
      .join("\n") || "No valid numeric probabilities were produced by the CT model.";

  const topClass =
    typeof analysisResult?.top_class === "string"
      ? analysisResult.top_class
      : entries.sort((a, b) => Number(b[1]) - Number(a[1]))[0]?.[0] || "Unknown";

  const prompt = `
You are a radiology assistant. You receive classification outputs from a chest CT scan model.

Patient details:
- Name: ${patient.fullName || "N/A"}
- Age: ${patient.age || "N/A"}
- Gender: ${patient.gender || "N/A"}
- Scan type: ${patient.scanType || "ctscan"}
- Overall abnormality confidence (higher = more confident scan is normal): ${patient.confidence}% 
- Model assessment flag: ${patient.isAbnormal ? "Flagged as abnormal" : "Likely normal"}
- Top predicted CT class: ${topClass}

Model CT class probabilities:
${findings}

Instructions:
1. Based on the CT class probabilities and the top predicted class, explain whether the scan is more suggestive of COVID, Pneumonia, or a normal appearance. If probabilities are close, clearly say that there is uncertainty.
2. Clearly state whether the overall CT findings suggest a likely abnormal scan or could be within normal limits.
3. Then give a brief technical note for clinicians (2–4 bullet points) that refers to the CT-specific findings (COVID vs Pneumonia vs Normal).
4. Do NOT invent contradictions; if the numeric outputs look coherent, do not say that outputs are inconsistent or missing.
5. Include a short confidentiality and safety note (data handled securely, this is not a medical diagnosis).
6. Do NOT mention logits or implementation details.

Return the answer in plain text, no markdown.
`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${GEMINI_API_KEY}`;

  const body = {
    contents: [
      {
        role: "user",
        parts: [{ text: prompt }],
      },
    ],
  };

  const resp = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });

  if (!resp.ok) {
    const errText = await resp.text();
    throw new Error(
      `Gemini API error ${resp.status}: ${errText || resp.statusText}`
    );
  }

  const data = await resp.json();
  const text =
    data?.candidates?.[0]?.content?.parts?.[0]?.text ||
    "No report generated by Gemini.";

  return text.trim();
}

export async function generateMRIReport(patient, analysisResult) {
  if (!GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY is not set in environment variables");
  }

  // analysisResult from run_mri.py:
  // { classes: [...], scores: { No_Tumor: 0.xx, Benign_Tumor: 0.xx, Malignant_Tumor: 0.xx }, top_class: "..." }
  const scoresObj =
    analysisResult && typeof analysisResult === "object"
      ? analysisResult.scores || analysisResult
      : {};

  const entries = Object.entries(scoresObj).filter(
    ([, v]) => typeof v === "number"
  );

  const findings =
    entries
      .map(([label, prob]) => {
        const p = Number(prob);
        return `${label}: ${(p * 100).toFixed(2)}%`;
      })
      .join("\n") ||
    "No valid numeric probabilities were produced by the MRI model.";

  const topClass =
    typeof analysisResult?.top_class === "string"
      ? analysisResult.top_class
      : entries.sort((a, b) => Number(b[1]) - Number(a[1]))[0]?.[0] ||
        "Unknown";

  const prompt = `
You are a radiology assistant. You receive classification outputs from a brain MRI tumor model.

Patient details:
- Name: ${patient.fullName || "N/A"}
- Age: ${patient.age || "N/A"}
- Gender: ${patient.gender || "N/A"}
- Scan type: ${patient.scanType || "mri"}
- Overall abnormality confidence (higher = more confident scan is normal): ${patient.confidence}% 
- Model assessment flag: ${patient.isAbnormal ? "Flagged as abnormal" : "Likely normal"}
- Top predicted MRI class: ${topClass}

Model MRI class probabilities:
${findings}

Instructions:
1. Based on the MRI class probabilities and the top predicted class, explain whether the scan suggests no tumor, a likely benign tumor, or a likely malignant tumor. If probabilities are close, clearly say that there is uncertainty.
2. Clearly state whether the overall MRI findings suggest a likely abnormal scan or could be within normal limits.
4. Then give a brief technical note for clinicians (2–4 bullet points) that refers to the MRI-specific findings.
5. Do NOT invent contradictions; if the numeric outputs look coherent, do not say that outputs are inconsistent or missing.
6. Include a short confidentiality and safety note (data handled securely, this is not a medical diagnosis).
7. Do NOT mention logits or implementation details.

Return the answer in plain text, no markdown.
`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${GEMINI_API_KEY}`;

  const body = {
    contents: [
      {
        role: "user",
        parts: [{ text: prompt }],
      },
    ],
  };

  const resp = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });

  if (!resp.ok) {
    const errText = await resp.text();
    throw new Error(
      `Gemini API error ${resp.status}: ${errText || resp.statusText}`
    );
  }

  const data = await resp.json();
  const text =
    data?.candidates?.[0]?.content?.parts?.[0]?.text ||
    "No report generated by Gemini.";

  return text.trim();
}